language: node_js
node_js:
  - "stable"
jobs:
  include:
    - stage: test
      script: npm install
    - stage: deploy
      script: npm run dev
    - stage: test integration
      script: npm run test